INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Nicholson', 'Jack', '80', 'male', '+(380) 505-55-00');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Jolie', 'Angelina', '45', 'female', '+(380) 450-62-65');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Crowe', 'Russell', '50', 'male', '+(380) 756-63-45');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Washington', 'Denzel', '55', 'male', '+(380) 956-42-33');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('De Niro', 'Robert', '70', 'male', '+(380) 350-11-22');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Theron', 'Charlize', '45', 'female', '+(380) 777-12-32');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Knightley', 'Keira', '35', 'female', '+(380) 897-78-59');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Damon', 'Matt', '45', 'male', '+(380) 258-36-69');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Zeta-Jones', 'Catherine', '50', 'female', '+(380) 123-45-78');
INSERT INTO `contactbook`.`user` (`lastName`, `firstName`, `age`, `gender`, `phonenumber`) VALUES ('Gibson', 'Mel', '70', 'male', '+(380) 977-28-11');